ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: pm.cagatayuresin.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true
    secretName: openproject-tls

postgresql:
  enabled: true
  auth:
    existingSecret: openproject-db-secret
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password

persistence:
  enabled: true
  size: 5Gi
