ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: pm.cagatayuresin.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: openproject-tls
      hosts:
        - pm.cagatayuresin.com

persistence:
  enabled: true
  size: 5Gi

postgresql:
  enabled: true
  auth:
    existingSecret: openproject-db-secret
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
