apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openproject
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.openproject.org/
    chart: openproject
    targetRevision: 1.10.1
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openproject
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
