ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: pm.cagatayuresin.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - pm.cagatayuresin.com
      secretName: openproject-tls

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi

postgresql:
  enabled: true
  auth:
    existingSecret: openproject-secrets
    secretKeys:
      adminPasswordKey: postgresqlPassword

configuration:
  defaultAdmin:
    existingSecret: openproject-secrets
    usernameKey: adminUsername
    passwordKey: adminPassword

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi
